language: php

sudo: false

php:
  - 7.1
  - 7.2

cache:
    directories:
        - $HOME/.composer/cache
        - .phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR=.phpunit

install:
    - composer --prefer-dist install
    - ./vendor/bin/simple-phpunit install

script: ./vendor/bin/simple-phpunit